"""add strain_favorites

Revision ID: 34fdfb1c6523
Revises: a8adc87534d4
Create Date: 2026-06-07 08:58:09.739538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fdfb1c6523'
down_revision: Union[str, None] = 'a8adc87534d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strain_favorites',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('strain_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_strain_favorites_player_id_players')),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], name=op.f('fk_strain_favorites_strain_id_strains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strain_favorites'))
    )
    with op.batch_alter_table('strain_favorites', schema=None) as batch_op:
        batch_op.create_index('ix_fav_player_strain', ['player_id', 'strain_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strain_favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_fav_player_strain')

    op.drop_table('strain_favorites')
    # ### end Alembic commands ###
