"""initial game schema

Revision ID: 552ac943a9b7
Revises: 
Create Date: 2026-06-07 08:06:45.711242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552ac943a9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('algorand_address', sa.String(length=64), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('email', name=op.f('uq_players_email')),
    sa.UniqueConstraint('username', name=op.f('uq_players_username'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_algorand_address'), ['algorand_address'], unique=False)

    op.create_table('grow_pods',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('co2_level', sa.Float(), nullable=True),
    sa.Column('light_intensity', sa.Float(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_grow_pods_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grow_pods'))
    )
    op.create_table('ledger_entries',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('onchain_txid', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_ledger_entries_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_player_created', ['player_id', 'created_at'], unique=False)

    op.create_table('market_listings',
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_ref_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['players.id'], name=op.f('fk_market_listings_buyer_id_players')),
    sa.ForeignKeyConstraint(['seller_id'], ['players.id'], name=op.f('fk_market_listings_seller_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings'))
    )
    op.create_table('strains',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('lineage_type', sa.String(length=16), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('indica_ratio', sa.Float(), nullable=False),
    sa.Column('thc_min', sa.Float(), nullable=False),
    sa.Column('thc_max', sa.Float(), nullable=False),
    sa.Column('cbd_min', sa.Float(), nullable=False),
    sa.Column('cbd_max', sa.Float(), nullable=False),
    sa.Column('flowering_days_min', sa.Integer(), nullable=False),
    sa.Column('flowering_days_max', sa.Integer(), nullable=False),
    sa.Column('yield_min', sa.Float(), nullable=False),
    sa.Column('yield_max', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('terpenes', sa.JSON(), nullable=True),
    sa.Column('genome', sa.JSON(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('parent_a_id', sa.String(length=32), nullable=True),
    sa.Column('parent_b_id', sa.String(length=32), nullable=True),
    sa.Column('is_base_catalog', sa.Boolean(), nullable=False),
    sa.Column('created_by_player_id', sa.String(length=32), nullable=True),
    sa.Column('nft_asset_id', sa.Integer(), nullable=True),
    sa.Column('nft_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_player_id'], ['players.id'], name=op.f('fk_strains_created_by_player_id_players')),
    sa.ForeignKeyConstraint(['parent_a_id'], ['strains.id'], name=op.f('fk_strains_parent_a_id_strains')),
    sa.ForeignKeyConstraint(['parent_b_id'], ['strains.id'], name=op.f('fk_strains_parent_b_id_strains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strains')),
    sa.UniqueConstraint('slug', name=op.f('uq_strains_slug'))
    )
    with op.batch_alter_table('strains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strains_rarity'), ['rarity'], unique=False)

    op.create_table('wallets',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('cached_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('asa_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_wallets_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('player_id', name=op.f('uq_wallets_player_id'))
    )
    op.create_table('breeding_events',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('parent_a_id', sa.String(length=32), nullable=False),
    sa.Column('parent_b_id', sa.String(length=32), nullable=False),
    sa.Column('offspring_strain_id', sa.String(length=32), nullable=True),
    sa.Column('rng_seed', sa.Integer(), nullable=False),
    sa.Column('inherited_traits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['offspring_strain_id'], ['strains.id'], name=op.f('fk_breeding_events_offspring_strain_id_strains')),
    sa.ForeignKeyConstraint(['parent_a_id'], ['strains.id'], name=op.f('fk_breeding_events_parent_a_id_strains')),
    sa.ForeignKeyConstraint(['parent_b_id'], ['strains.id'], name=op.f('fk_breeding_events_parent_b_id_strains')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_breeding_events_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breeding_events'))
    )
    op.create_table('environment_readings',
    sa.Column('pod_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('co2_level', sa.Float(), nullable=False),
    sa.Column('light_intensity', sa.Float(), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['grow_pods.id'], name=op.f('fk_environment_readings_pod_id_grow_pods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_readings'))
    )
    with op.batch_alter_table('environment_readings', schema=None) as batch_op:
        batch_op.create_index('ix_env_pod_ts', ['pod_id', 'timestamp'], unique=False)

    op.create_table('seed_inventory',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('strain_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('feminized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_seed_inventory_player_id_players')),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], name=op.f('fk_seed_inventory_strain_id_strains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_inventory'))
    )
    with op.batch_alter_table('seed_inventory', schema=None) as batch_op:
        batch_op.create_index('ix_seed_player_strain', ['player_id', 'strain_id'], unique=False)

    op.create_table('plants',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('pod_id', sa.String(length=32), nullable=False),
    sa.Column('strain_id', sa.String(length=32), nullable=False),
    sa.Column('seed_id', sa.String(length=32), nullable=True),
    sa.Column('genome', sa.JSON(), nullable=False),
    sa.Column('growth_stage', sa.String(length=16), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=False),
    sa.Column('nutrient_level', sa.Float(), nullable=False),
    sa.Column('pest_level', sa.Float(), nullable=False),
    sa.Column('disease_level', sa.Float(), nullable=False),
    sa.Column('condition_flags', sa.JSON(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('harvested', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_plants_player_id_players')),
    sa.ForeignKeyConstraint(['pod_id'], ['grow_pods.id'], name=op.f('fk_plants_pod_id_grow_pods')),
    sa.ForeignKeyConstraint(['seed_id'], ['seed_inventory.id'], name=op.f('fk_plants_seed_id_seed_inventory')),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], name=op.f('fk_plants_strain_id_strains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants'))
    )
    op.create_table('growth_measurements',
    sa.Column('plant_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('leaf_count', sa.Integer(), nullable=True),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_growth_measurements_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_measurements'))
    )
    with op.batch_alter_table('growth_measurements', schema=None) as batch_op:
        batch_op.create_index('ix_growth_plant_ts', ['plant_id', 'timestamp'], unique=False)

    op.create_table('harvests',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('plant_id', sa.String(length=32), nullable=False),
    sa.Column('strain_id', sa.String(length=32), nullable=False),
    sa.Column('harvested_at', sa.DateTime(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('thc_actual', sa.Float(), nullable=True),
    sa.Column('cbd_actual', sa.Float(), nullable=True),
    sa.Column('rarity_snapshot', sa.String(length=16), nullable=False),
    sa.Column('sale_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=False),
    sa.Column('nft_asset_id', sa.Integer(), nullable=True),
    sa.Column('nft_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_harvests_plant_id_plants')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_harvests_player_id_players')),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], name=op.f('fk_harvests_strain_id_strains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harvests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvests')
    with op.batch_alter_table('growth_measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_plant_ts')

    op.drop_table('growth_measurements')
    op.drop_table('plants')
    with op.batch_alter_table('seed_inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_seed_player_strain')

    op.drop_table('seed_inventory')
    with op.batch_alter_table('environment_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_env_pod_ts')

    op.drop_table('environment_readings')
    op.drop_table('breeding_events')
    op.drop_table('wallets')
    with op.batch_alter_table('strains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strains_rarity'))

    op.drop_table('strains')
    op.drop_table('market_listings')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_player_created')

    op.drop_table('ledger_entries')
    op.drop_table('grow_pods')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_algorand_address'))

    op.drop_table('players')
    # ### end Alembic commands ###
