"""add player xp and level

Revision ID: 5742217f7cda
Revises: a1c3af89c788
Create Date: 2026-06-07 08:36:16.700731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5742217f7cda'
down_revision: Union[str, None] = 'a1c3af89c788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
