"""add ftue progress columns to players

Revision ID: 9d669edf48a8
Revises: c7ecd7523cc8
Create Date: 2026-06-14 07:29:52.987849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d669edf48a8'
down_revision: Union[str, None] = 'c7ecd7523cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        # server_default backfills existing rows so the NOT NULL add succeeds on a
        # populated table; the ORM sets ftue_step explicitly on new players.
        batch_op.add_column(sa.Column('ftue_step', sa.String(length=32), nullable=False, server_default='welcome'))
        batch_op.add_column(sa.Column('ftue_plant_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ftue_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('ftue_completed_at')
        batch_op.drop_column('ftue_plant_id')
        batch_op.drop_column('ftue_step')

    # ### end Alembic commands ###
