"""add plant_events for simulation

Revision ID: a1c3af89c788
Revises: 552ac943a9b7
Create Date: 2026-06-07 08:18:35.154475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c3af89c788'
down_revision: Union[str, None] = '552ac943a9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_events',
    sa.Column('plant_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_plant_events_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plant_events'))
    )
    with op.batch_alter_table('plant_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_plant_ts', ['plant_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_plant_ts')

    op.drop_table('plant_events')
    # ### end Alembic commands ###
