"""add player api_key

Revision ID: a8adc87534d4
Revises: 5742217f7cda
Create Date: 2026-06-07 08:50:17.757473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8adc87534d4'
down_revision: Union[str, None] = '5742217f7cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
