"""add grant_claims starter-grant rail

Revision ID: c7ecd7523cc8
Revises: c3d4e5f6a7b8
Create Date: 2026-06-14 06:09:07.279519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ecd7523cc8'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_claims',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('grant_type', sa.String(length=32), nullable=False),
    sa.Column('grant_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_grant_claims_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grant_claims'))
    )
    with op.batch_alter_table('grant_claims', schema=None) as batch_op:
        batch_op.create_index('uq_grant_claims_player_type_key', ['player_id', 'grant_type', 'grant_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant_claims', schema=None) as batch_op:
        batch_op.drop_index('uq_grant_claims_player_type_key')

    op.drop_table('grant_claims')
    # ### end Alembic commands ###
