"""add contracts

Revision ID: ea3d4cde6593
Revises: f58d1449192b
Create Date: 2026-06-07 09:13:57.312867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3d4cde6593'
down_revision: Union[str, None] = 'f58d1449192b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('target_rarity', sa.String(length=16), nullable=True),
    sa.Column('target_grams', sa.Float(), nullable=False),
    sa.Column('reward_grow', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_contracts_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contract_player_status', ['player_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_player_status')

    op.drop_table('contracts')
    # ### end Alembic commands ###
