"""add pod automation flags

Revision ID: f58d1449192b
Revises: 34fdfb1c6523
Create Date: 2026-06-07 09:06:01.866615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58d1449192b'
down_revision: Union[str, None] = '34fdfb1c6523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grow_pods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_water', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('auto_feed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grow_pods', schema=None) as batch_op:
        batch_op.drop_column('auto_feed')
        batch_op.drop_column('auto_water')

    # ### end Alembic commands ###
