"""wallet link challenges table (signed-challenge wallet auth)

Disruptor-sweep finding #4 (docs/memory/standups/2026-07-06-disruptor-sweep.md):
`link_wallet` only checksum-validated an address, so anyone could claim a
public address they read off the unauthenticated listings feed and then
authorize marketplace/staking actions off that spoofed link. `a3f6c1d8b920`
added a defense-in-depth uniqueness constraint; this migration adds the real
fix -- a one-time nonce the caller must sign with the address's private key
(verified server-side in `services/wallet_auth.py`) before `link_wallet`
trusts it. New table only, no existing columns touched.

Revision ID: f67be25fe8e1
Revises: a3f6c1d8b920
Create Date: 2026-07-06 22:36:33.674613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67be25fe8e1'
down_revision: Union[str, None] = 'a3f6c1d8b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_link_challenges',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_wallet_link_challenges_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_link_challenges'))
    )
    with op.batch_alter_table('wallet_link_challenges', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_challenge_player', ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_link_challenges_nonce'), ['nonce'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_link_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_link_challenges_nonce'))
        batch_op.drop_index('ix_wallet_challenge_player')

    op.drop_table('wallet_link_challenges')
    # ### end Alembic commands ###
