"""add auction fields to market_listings

Revision ID: fbb8fceedacd
Revises: ea3d4cde6593
Create Date: 2026-06-07 09:16:39.141616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb8fceedacd'
down_revision: Union[str, None] = 'ea3d4cde6593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auction', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('min_bid', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('highest_bid', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('highest_bidder_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_market_listings_highest_bidder_id_players'), 'players', ['highest_bidder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_market_listings_highest_bidder_id_players'), type_='foreignkey')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('highest_bidder_id')
        batch_op.drop_column('highest_bid')
        batch_op.drop_column('min_bid')
        batch_op.drop_column('is_auction')

    # ### end Alembic commands ###
