// Engine 3 — Phyllotaxy. Pure, deterministic, DOM-free (unit-tested under vitest).
//
// Real cannabis sets its leaves/branches on a schedule the meristem decides, not
// in a flat left↔right plane: seedlings start OPPOSITE (decussate, ~180° flips),
// then transition to an ALTERNATE golden-angle spiral (~137.5077°) as they mature.
// The legacy chamber placed every node hard-left or hard-right in one picture
// plane, so plants read as a symmetric diagram and every fan leaf billboarded at
// the camera. This module gives each node a true AZIMUTH around the stem, which
// the renderer projects into pseudo-3D (horizontal foreshortening + front/back
// depth) so branches wrap around the stalk and leaves face away from the camera.
//
// It is built so that, at the seedling end of the transition, it reproduces the
// legacy flat alternation EXACTLY — young/veg plants stay recognisable — and only
// blooms into spiral depth as the plant matures.

import { clamp, lerp, smooth } from "./morphology";

/** The golden angle in radians: π·(3−√5) ≈ 2.399963 rad = 137.5077°. */
export const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));

export interface NodeAzimuth {
  /** Azimuth around the stem (radians), 0 = toward +x (screen right). */
  az: number;
  /** cos(az) ∈ [-1,1] — signed horizontal projection (also the foreshortening). */
  lateral: number;
  /** sin(az) ∈ [-1,1] — depth: +1 toward the camera (front), −1 away (back). */
  depth: number;
  /** sign(lateral) — the legacy ±1 "side" for sign-dependent branch geometry. */
  side: 1 | -1;
}

/**
 * Phyllotactic azimuths for a stack of `count` nodes (index 0 = base → apex).
 *
 * The pattern is generated by CUMULATIVE angular steps, each lerping from a 180°
 * opposite flip toward the 137.5° golden angle. With every step at 180° the result
 * is the legacy flat left/right alternation (lateral = ±1, depth = 0); as steps
 * shorten to the golden angle the nodes wind into a spiral that wraps front↔back.
 *
 * @param count    number of nodes (>= 0).
 * @param maturity 0..1 — how far the golden spiral has taken over (veg ≈ low →
 *                 flower ≈ high). Also scaled per-node so lower/older nodes stay
 *                 more opposite and the apex spirals first (botanically true).
 * @param phase    per-plant starting azimuth (radians) so no two plants align.
 */
export function phyllotaxis(count: number, maturity: number, phase = 0): NodeAzimuth[] {
  const m = clamp(maturity, 0, 1);
  const out: NodeAzimuth[] = [];
  let az = phase;
  for (let i = 0; i < count; i++) {
    if (i > 0) {
      // Lower nodes stay opposite; the spiral takes over toward the apex. The
      // −0.18 offset keeps the first couple of node-pairs decussate (as a real
      // seedling does) before the golden angle eases in.
      const up = count > 1 ? i / (count - 1) : 0;
      const t = smooth(clamp((up - 0.18) / 0.52, 0, 1)) * m;
      az += lerp(Math.PI, GOLDEN_ANGLE, t);
    }
    const lateral = Math.cos(az);
    out.push({
      az,
      lateral,
      depth: Math.sin(az),
      side: lateral >= 0 ? 1 : -1,
    });
  }
  return out;
}

/**
 * Horizontal foreshortening for a branch/leaf at azimuth lateral=cos(az): a node
 * facing the camera (lateral≈0) keeps a floor of visible length (it angles toward
 * the viewer rather than vanishing), a node facing fully sideways (|lateral|=1) is
 * at full length. Keeps camera-facing branches readable instead of collapsing.
 */
export function foreshorten(lateral: number, floor = 0.42): number {
  return lerp(floor, 1, Math.abs(clamp(lateral, -1, 1)));
}

/**
 * Atmospheric depth shade (lightness delta, in HSL % points) for a node at the
 * given depth: front (+1) reads a touch brighter, back (−1) a touch darker, so the
 * canopy gains volume. Bounded and gentle — depth cue, not a spotlight.
 */
export function depthShade(depth: number, amount = 7): number {
  return clamp(depth, -1, 1) * amount;
}
